apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: api
  creationTimestamp: null
  labels:
    app: poi
  name: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: poi
    spec:
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kv-provider"
          # nodePublishSecretRef: 
          #   name: akv-creds 
      containers:
      - image: registryycv7004.azurecr.io/tripinsights/poi:1.0
        name: poi-container
        ports:
          - containerPort: 80
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: TESTENV
            value: TESTENVVALUE
          # - name: mysecretinpod
            # valueFrom:
            #   secretKeyRef:
            #     name: mykeyvaultsecret
            #     key: testsecret
        envFrom:
          - secretRef:
              name: sql-server-secret
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: api
  creationTimestamp: null
  labels:
    app: poi
  name: poi-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: poi
  type: ClusterIP
status:
  loadBalancer: {}
