kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-user-full-access-role
  namespace: web
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-user-access-rolebinding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-user-full-access-role
subjects:
- kind: Group
  namespace: web
  #name: groupObjectId
  name: "a0b41752-c348-4ce8-892f-2b41eeeaa975"  



  
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-user-read-only-api-access-role
  namespace: web
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get","list","watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-user-read-only-api-access-rolebinding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-user-read-only-api-access-role
subjects:
- kind: Group
  namespace: web
  #name: groupObjectId
  name: "a0b41752-c348-4ce8-892f-2b41eeeaa975"  
